version: '3.8'

services:
  arch_ref:
    image: arch_ref:1.2
    depends_on:
      - postgres
    environment:
      password: ${password}
      databaseurl: ${databaseurl}
      username: ${username}
    ports:
      - "8080:8080"

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres:
